# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('ofswitch13-example', ['ofswitch13', 'csma', 'network', 'applications', 'internet'])
    obj.source = 'ofswitch13-example.cc'

    obj = bld.create_ns3_program('ofswitch13-duplo', ['ofswitch13', 'csma', 'network', 'applications', 'internet'])
    obj.source = 'ofswitch13-duplo.cc'


